// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_testes_introduction/test/item_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_testes_introduction/item.dart' as _i2;
import 'package:flutter_testes_introduction/item_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeItem_0 extends _i1.SmartFake implements _i2.Item {
  _FakeItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemRepository extends _i1.Mock implements _i3.ItemRepository {
  MockItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Item>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Item>>.value(<_i2.Item>[]),
      ) as _i4.Future<List<_i2.Item>>);

  @override
  List<_i2.Item> getAllSync() => (super.noSuchMethod(
        Invocation.method(
          #getAllSync,
          [],
        ),
        returnValue: <_i2.Item>[],
      ) as List<_i2.Item>);

  @override
  _i2.Item getByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getByName,
          [name],
        ),
        returnValue: _FakeItem_0(
          this,
          Invocation.method(
            #getByName,
            [name],
          ),
        ),
      ) as _i2.Item);
}
